// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfayvtcwdhfkvtuhuubp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmYXl2dGN3ZGhma3Z0dWh1dWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzAxMjgsImV4cCI6MjA2OTA0NjEyOH0.NmcO0LZK2ajarGYDd249VfDcFvfy2vuPQ2AVWFxsuc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});