name: Build e Upload iOS com Fastlane

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
      APP_IDENTIFIER: com.prosoccerapp.prohealthapp
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Fastlane
        run: gem install fastlane

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Build do Vite
        run: npm run build

      - name: Adicionar iOS e sincronizar Capacitor
        run: |
          npx cap add ios || true
          npx cap sync

      - name: Instalar CocoaPods
        run: |
          cd ios/App
          pod install

      - name: Criar chave privada para App Store Connect
        run: echo "${APPLE_KEY_CONTENT}" > AuthKey.p8

      - name: Fastlane build
        run: |
          cd ios/App
          fastlane produce \
            --username "$APP_STORE_EMAIL" \
            --app_identifier "$APP_IDENTIFIER" \
            --team_id "$APPLE_TEAM_ID" || true

          fastlane match appstore \
            --type appstore \
            --readonly \
            --team_id "$APPLE_TEAM_ID" \
            --app_identifier "$APP_IDENTIFIER" \
            --key_id "$APPLE_KEY_ID" \
            --issuer_id "$APPLE_ISSUER_ID" \
            --key_content "$APPLE_KEY_CONTENT"

          fastlane gym \
            --scheme App \
            --export_method app-store \
            --export_options '{
              "signingStyle": "automatic",
              "compileBitcode": false,
              "stripSwiftSymbols": true,
              "method": "app-store"
            }'

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ios
          path: ios/App/*.ipa
