name: FastlaneV4

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14 # ✅ Xcode 16 requer macOS 14
    timeout-minutes: 60

    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      APP_IDENTIFIER: com.prosoccerapp.prohealthappv2
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'


      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - run: gem install fastlane

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --legacy-peer-deps
      - run: NODE_ENV=production npm run build:cap

      - run: rm -rf ios
      - run: |
          npx cap add ios
          npx cap sync

      - name: Criar arquivo de Entitlements com suporte ao HealthKit
        run: |
          cat <<EOF > ios/App/App/App.entitlements
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>com.apple.developer.healthkit</key>
            <true/>
          </dict>
          </plist>
          EOF
          
      - name: Limpar cache do CocoaPods
        run: |
          rm -rf ios/App/Pods ios/App/Podfile.lock ~/Library/Caches/CocoaPods

      - run: |
          cd ios/App
          pod install

      - name: Ensure scripts are executable
        run: chmod +x ios/App/Pods/Target\ Support\ Files/Pods-App/Pods-App-frameworks.sh

      - name: Debug Embed Frameworks Script
        run: |
          echo 'Modificando script de Embed Pods para imprimir frameworks sendo processados...'
          sed -i '' 's/echo "Code Signing \$1"/echo "📦 Embedding framework: \$1"/' ios/App/Pods/Target\ Support\ Files/Pods-App/Pods-App-frameworks.sh || echo "Não foi possível modificar script"

      - name: Exibir Pods Instalados e Configurações
        run: |
          echo "📄 Conteúdo do Podfile.lock:"
          cat ios/App/Podfile.lock || echo "Podfile.lock não encontrado"
      
          echo ""
          echo "📂 Estrutura do diretório Pods:"
          find ios/App/Pods -type f -name "*.podspec.json" || echo "Nenhum podspec encontrado"
      
          echo ""
          echo "🔍 Build Settings (parciais) dos Pods:"
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -showBuildSettings | grep -E "Pods-|PODS|SWIFT_VERSION|CODE_SIGN|FRAMEWORK" || echo "Não foi possível extrair build settings"

      - name: Patch Bundle Identifier
        run: |
          sed -i '' 's/com.prosoccerapp.prohealthapp/com.prosoccerapp.prohealthappv2/g' ios/App/App.xcodeproj/project.pbxproj

      - name: Generate Fastfile
        run: |
          mkdir -p ios/App/fastlane
          cat <<EOF > ios/App/fastlane/Fastfile
          default_platform(:ios)

          platform :ios do
            lane :release do
              api_key = app_store_connect_api_key(
                key_id: ENV["APPLE_KEY_ID"],
                issuer_id: ENV["APPLE_ISSUER_ID"],
                key_content: ENV["APPLE_KEY_CONTENT"],
                is_key_content_base64: false
              )
            
              match(
                type: "appstore",
                readonly: false,
                git_url: ENV["MATCH_GIT_URL"],
                app_identifier: ENV["APP_IDENTIFIER"],
                api_key: api_key
              )
            
              sh("security set-key-partition-list -S apple-tool:,apple: -s -k buildpass build.keychain")

              update_project_team(
                path: "App.xcodeproj",
                teamid: ENV["APPLE_TEAM_ID"]
              )
              
              update_code_signing_settings(
                use_automatic_signing: false,
                path: "App.xcodeproj",
                code_sign_identity: "Apple Distribution",
                profile_name: "match AppStore com.prosoccerapp.prohealthappv2",
                team_id: ENV["APPLE_TEAM_ID"],
                bundle_identifier: ENV["APP_IDENTIFIER"]
              )

              update_project_provisioning(
                xcodeproj: "App.xcodeproj",
                target_filter: "App",
                profile: "match AppStore com.prosoccerapp.prohealthappv2",
                build_configuration: "Release",
                code_signing_identity: "Apple Distribution",
                entitlements_file: "App/App.entitlements"
              )

              clear_derived_data
              
              build_app(
                scheme: "App",
                clean: true,
                export_method: "app-store",
                export_team_id: ENV["APPLE_TEAM_ID"],
                # ✅ Evita embed dos frameworks indevidos
                xcargs: "ARCHS=arm64 DEVELOPMENT_TEAM=#{ENV["APPLE_TEAM_ID"]} CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=\"Apple Distribution\"",
                disable_xcpretty: true,
                export_options: {
                  provisioningProfiles: {
                    "com.prosoccerapp.prohealthappv2" => "match AppStore com.prosoccerapp.prohealthappv2"
                  },
                  signingStyle: "manual",
                  signingCertificate: "Apple Distribution",
                  teamID: ENV["APPLE_TEAM_ID"]
                }
              )

              upload_to_testflight(
                api_key: api_key,
                app_identifier: ENV["APP_IDENTIFIER"]
              )
            end
          end
          EOF

      - name: Verificar script Embed Pods Frameworks
        run: |
          echo "📜 Conteúdo do script [CP] Embed Pods Frameworks:"
          cat ios/App/Pods/Target\ Support\ Files/Pods-App/Pods-App-frameworks.sh || echo "Script não encontrado"

      - name: Clean DerivedData
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Configurar keychain para uso com match
        run: |
          KEYCHAIN_NAME=build.keychain
          KEYCHAIN_PASSWORD=buildpass

          echo "🔐 Criando keychain"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"

          echo "📂 Definindo como keychain default"
          security default-keychain -s "$KEYCHAIN_NAME"

          echo "🔓 Desbloqueando keychain"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"

      - name: Exportar variáveis de keychain para o Fastlane
        run: |
          echo "MATCH_KEYCHAIN_NAME=build.keychain" >> $GITHUB_ENV
          echo "MATCH_KEYCHAIN_PASSWORD=buildpass" >> $GITHUB_ENV

      - name: Adicionar NSHealthUsage ao Info.plist
        run: |
          /usr/libexec/PlistBuddy -c "Add :NSHealthShareUsageDescription string 'Este app pode utilizar bibliotecas que acessam dados de saúde. Nenhuma informação será usada sem sua permissão.'" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Add :NSHealthUpdateUsageDescription string 'Este app pode utilizar bibliotecas que atualizam dados de saúde. Nenhuma informação será usada sem sua permissão.'" ios/App/App/Info.plist

      - name: Aumentar build number automaticamente
        run: |
          BUILD_NUMBER=$(date +%s) # ou algum outro sistema, como contador no repositório
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/App/App/Info.plist

      - run: ls -l www || echo "⚠️ Pasta 'www' não encontrada"
      
      - run: npx cap copy ios
      
      - name: Pré-build
        run: echo "🏗️ Iniciando build..."

      - name: Run Fastlane
        run: |
          cd ios/App
          fastlane release

      - name: Pós-build
        run: echo "✅ Build finalizado com sucesso"

      - uses: actions/upload-artifact@v4
        with:
          name: app-ios
          path: ios/App/*.ipa

      - name: Show build log if failure
        if: failure()
        run: |
          cat ~/Library/Logs/gym/App-App.log || echo "Log não encontrado"
