name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      IOS_CERTIFICATE: ${{ secrets.IOS_CERTIFICATE }}
      IOS_CERT_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD }}
      IOS_PROFILE: ${{ secrets.IOS_PROFILE }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Build Vite
        run: npm run build

      - name: Instalar Capacitor
        run: npm install -g @capacitor/cli

      - name: Limpar pasta iOS (caso exista)
        run: rm -rf ios

      - name: Adicionar iOS
        run: npx cap add ios

      - name: Sincronizar Capacitor
        run: npx cap sync

      - name: Instalar dependências nativas iOS (CocoaPods)
        run: |
          cd ios/App
          pod install

      - name: Corrigir assinatura dos Pods para Automática
        run: |
          find ios/App/Pods -name "project.pbxproj" | while read proj; do
            sed -i '' 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g' "$proj"
            sed -i '' 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' "$proj"
            sed -i '' 's/CODE_SIGNING_ALLOWED = YES;/CODE_SIGNING_ALLOWED = NO;/g' "$proj"
          done
          
      - name: Preparar certificado
        run: |
          echo "$IOS_CERTIFICATE" | base64 --decode > certificate.p12
          echo "$IOS_PROFILE" | base64 --decode > profile.mobileprovision
          security create-keychain -p github ios-build.keychain
          security default-keychain -s ios-build.keychain
          security unlock-keychain -p github ios-build.keychain
          security import certificate.p12 -k ios-build.keychain -P "$IOS_CERT_PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Criar release.xcconfig
        run: |
          echo "DEVELOPMENT_TEAM = $APPLE_TEAM_ID" > ios/App/release.xcconfig
          echo "CODE_SIGN_STYLE = Manual" >> ios/App/release.xcconfig
          echo "CODE_SIGN_IDENTITY = Apple Distribution" >> ios/App/release.xcconfig
          echo "PROVISIONING_PROFILE_SPECIFIER = " >> ios/App/release.xcconfig

      - name: Criar exportOptions.plist
        run: |
          cat <<EOF > ios/App/exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>${APPLE_TEAM_ID}</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>app.lovable.7bde27a9721845aaa0217e78cef04596</key>
              <string>ProfileProHealth</string>
            </dict>
          </dict>
          </plist>
          EOF

      - name: Verificar Schemes disponíveis
        run: |
          cd ios/App
          xcodebuild -list

      - name: Build com Xcode
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          -xcconfig release.xcconfig \
          -archivePath $PWD/build/App.xcarchive \
          -allowProvisioningUpdates \
          PROVISIONING_PROFILE_SPECIFIER=ProfileProHealth \
          archive

      - name: Exportar IPA
        run: |
          set -x
          echo "::group::exportOptions.plist"
          cat ios/App/exportOptions.plist
          echo "::endgroup::"
      
          echo "::group::Conteúdo do .xcarchive"
          find ios/App/build/App.xcarchive
          echo "::endgroup::"
      
          xcodebuild -exportArchive -verbose \
            -archivePath ios/App/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath ios/App/build | tee ios/App/build/export-log.txt
        timeout-minutes: 10
        continue-on-error: true

      - name: Upload log de exportação
        uses: actions/upload-artifact@v4
        with:
          name: export-log
          path: ios/App/build/export-log.txt

      - name: Upload do .ipa
        uses: actions/upload-artifact@v4
        with:
          name: app-ios
          path: ios/App/build/*.ipa

      - name: Enviar para TestFlight
        run: |
          xcrun altool --upload-app --type ios --file ios/App/build/App.ipa \
            --username "$APPLE_ID" --password "$APP_SPECIFIC_PASSWORD"
